//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_SBAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int ContactID { get; set; }
        public byte ContactTypeID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<int> supplierID { get; set; }
        public string contact { get; set; }
        public string description { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
