//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_SBAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductByDepartment
    {
        public long productID { get; set; }
        public short departmentID { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public decimal price { get; set; }
        public Nullable<byte> markupPercent { get; set; }
        public Nullable<decimal> fixedPrice { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Products Products { get; set; }
    }
}
