//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_SBAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevisionDetails
    {
        public int revisionID { get; set; }
        public long productID { get; set; }
        public decimal retailPrice { get; set; }
        public decimal inBaseQuantity { get; set; }
        public Nullable<decimal> realQuantity { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Revision Revision { get; set; }
    }
}
