//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_SBAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public short userID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int ownerID { get; set; }
        public byte userRolesID { get; set; }
        public string salt { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual UserRoles UserRoles { get; set; }
    }
}
